### PR TITLE
fix (addon): #882 handle unload(reason="uninstall")

### LINKED ISSUE #882: Bug 1282053 - Activity Stream resource is not removed from "about:preferences->Home Page" field after uninstalling the add-on
via https://bugzilla.mozilla.org/show_bug.cgi?id=1282053
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.1.0-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.1.0-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Go to `about:preferences` and observe the Home Page resource.
3. Open `about:addons` in a new tab and click on "Remove" button.
4. Go back to `about:preferences` and observe the Home Page resource.

[Expected result]:
- Default `Mozilla Firefox Start Page` is set as Home Page.

[Actual result]:
- `resource://activity-streams/data/content/activity-streams.html#/` is set as Home Page.

[Notes]:
- When Activity Stream add-on is disabled, the resource from Home Page is removed and Default Mozilla Firefox Start Page is set as Home Page.
- Related to #724 .
- [Here](https://bug1282053.bmoattachments.org/attachment.cgi?id=8764888) is a screen recording of the issue.

### PR DESCRIPTION
**Pull request by rlr**
@oyiptong turns out unload is called with `reason="uninstall"` when uninstalling. mdn and bugzilla are wrong or outdated.

r?

Fixes #882

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-stream/884)

### CODE REVIEW

**Comment by oyiptong** [comment]
r+

**Comment by oyiptong** [comment]
we need to remove the homepage on disable as well

**Comment by oyiptong** [comment]
r+ with a nit

File: lib/ActivityStreams.js [hunk 1]
```diff
@@ -592,12 +592,10 @@ ActivityStreams.prototype = {
...
-
-      // note that if the user uninstalls the addon, the reason will be set as
-      // "disable", see more here https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/Listening_for_load_and_unload
+      // can be one of: uninstall/disable/shutdown/upgrade/downgrade
       case "disable":
-        this._tabTracker.handleUserEvent({event: "disable"});
+      case "uninstall":
+        this._tabTracker.handleUserEvent({event: reason});
         this._previewProvider.clearCache();
         this._unsetHomePage();
```
Comment (rlr) [inline lib/ActivityStreams.js]: this is called for both disable and uninstall, isn't it? /me reads up on js switch statements.

Comment (oyiptong) [inline lib/ActivityStreams.js]: yes that's correct
