### PR TITLE
shield(addon): Closes #1515 Try addon as shield study

### LINKED ISSUE #1515: Try add-on as shield experiment
Split from #1438. Just to see if anything unexpected happens just installing the add-on as shield.

### PR DESCRIPTION
**Pull request by sarracini**
SHIELD stuff 
Sets up the SHIELD and adds @Mardak's about:newtab ping injection patch from PR #1561 

See [doc](https://github.com/sarracini/activity-stream/blob/43adbabf34862b15872e65b318d6bb76584bdbed/SHIELD.md) about how to run this PR and how the study works

### CODE REVIEW

**Comment by Mardak** [comment]
Do we want to add a commit to handle #1575's change for `TabTracker._setCommonProperties` to set the appropriate `payload.page` for TILES vs `eventConstants.defaultPage` ?

I suppose we should be clear that this PR should *not* be merged into master and kept on a separate branch?

**Comment by sarracini** [comment]
Why do we even need a page in the payload for the ping? there's only one options for page now it seems redundant adding it to the payload

**Comment by Mardak** [comment]
Ah indeed. We could probably just remove page from the payload on master... @ncloudioj ?

And because we do have the shield variant value, for a search from newtab vs tiles, we'll be able to differentiate the two without the `page` field.

**Comment by ncloudioj** [comment]
Since `page` is a required field in the RS table, it needs some extra work to do "ALTER TABLE DROP COLUMN" there. Is it possible to just keep it, and use a default dummy value for the shield study?

**Comment by Mardak** [comment]
Okay, we can just leave the field/column, and it effectively has a "dummy" value already of "NEW_TAB". We don't need to do anything special for shield (and rely on `shield_variant`).

**Comment by Mardak** [comment]
@emtwo here are what the pings look like right now for tiles (search and a tile click):
```json
{
    "0LOAD": "shield-study-01-Tiles",
    "1PAYLOAD": {
        "action": "activity_stream_event",
        "addon_version": "1.1.5",
        "client_id": "3a65ccba-3981-cd49-b2eb-90b9c386ef93",
        "event": "SEARCH",
        "locale": "en-US",
        "page": "NEW_TAB",
        "session_id": "{22c2cb21-7361-5042-97b5-2d601a38782b}",
        "shield_variant": "shield-study-01-Tiles",
        "tab_id": "-3-2"
    },
    "2PING": {
        "action": "activity_stream_event",
        "addon_version": "1.1.5",
        "client_id": "3a65ccba-3981-cd49-b2eb-90b9c386ef93",
        "event": "SEARCH",
        "locale": "en-US",
        "page": "NEW_TAB",
        "session_id": "{22c2cb21-7361-5042-97b5-2d601a38782b}",
        "shield_variant": "shield-study-01-Tiles",
        "tab_id": "-3-2"
    },
    "3PING": {
        "action": "activity_stream_session",
        "addon_version": "1.1.5",
        "client_id": "3a65ccba-3981-cd49-b2eb-90b9c386ef93",
        "load_reason": "newtab",
        "locale": "en-US",
        "page": "NEW_TAB",
        "session_duration": 4315,
        "session_id": "{22c2cb21-7361-5042-97b5-2d601a38782b}",
        "tab_id": "-3-2",
        "total_bookmarks": 0,
        "total_history_size": 0,
        "unload_reason": "search",
        "url": "about:newtab"
    },
    "4PAYLOAD": {
        "action": "activity_stream_event",
        "action_position": 0,
        "addon_version": "1.1.5",
        "client_id": "3a65ccba-3981-cd49-b2eb-90b9c386ef93",
        "event": "CLICK",
        "locale": "en-US",
        "page": "NEW_TAB",
        "session_id": "{3bdaae07-9925-5f48-9536-fcfa7173b92e}",
        "shield_variant": "shield-study-01-Tiles",
        "source": "HISTORY",
        "tab_id": "-3-3"
    },
    "5PING": {
        "action": "activity_stream_event",
        "action_position": 0,
        "addon_version": "1.1.5",
        "client_id": "3a65ccba-3981-cd49-b2eb-90b9c386ef93",
        "event": "CLICK",
        "locale": "en-US",
        "page": "NEW_TAB",
        "session_id": "{3bdaae07-9925-5f48-9536-fcfa7173b92e}",
        "shield_variant": "shield-study-01-Tiles",
        "source": "HISTORY",
        "tab_id": "-3-3"
    },
    "6PING": {
        "action": "activity_stream_session",
        "addon_version": "1.1.5",
        "client_id": "3a65ccba-3981-cd49-b2eb-90b9c386ef93",
        "load_reason": "focus",
        "locale": "en-US",
        "page": "NEW_TAB",
        "session_duration": 3623,
        "session_id": "{3bdaae07-9925-5f48-9536-fcfa7173b92e}",
        "tab_id": "-3-3",
        "total_bookmarks": 0,
        "total_history_size": 0,
        "unload_reason": "click",
        "url": "about:newtab"
    }
}
```

And activity stream new tab (search, a top site click, a highlight click):
```json
{
    "0LOAD": "shield-study-01-ActivityStream",
    "1PAYLOAD": {
        "action": "activity_stream_event",
        "addon_version": "1.1.5",
        "client_id": "13a8f957-25aa-b745-b18d-e3b85d816cc1",
        "event": "SEARCH",
        "locale": "en-US",
        "page": "NEW_TAB",
        "session_id": "{c9ac5075-d18b-7847-8804-8e94d9ebffd7}",
        "shield_variant": "shield-study-01-ActivityStream",
        "tab_id": "-3-2"
    },
    "2PING": {
        "action": "activity_stream_event",
        "addon_version": "1.1.5",
        "client_id": "13a8f957-25aa-b745-b18d-e3b85d816cc1",
        "event": "SEARCH",
        "locale": "en-US",
        "page": "NEW_TAB",
        "session_id": "{c9ac5075-d18b-7847-8804-8e94d9ebffd7}",
        "shield_variant": "shield-study-01-ActivityStream",
        "tab_id": "-3-2"
    },
    "3PING": {
        "action": "activity_stream_session",
        "addon_version": "1.1.5",
        "client_id": "13a8f957-25aa-b745-b18d-e3b85d816cc1",
        "load_latency": 889,
        "load_reason": "newtab",
        "locale": "en-US",
        "page": "NEW_TAB",
        "session_duration": 9772,
        "session_id": "{c9ac5075-d18b-7847-8804-8e94d9ebffd7}",
        "tab_id": "-3-2",
        "total_bookmarks": 167,
        "total_history_size": 100014,
        "unload_reason": "search",
        "url": "resource://activity-streams/data/content/activity-streams.html#/"
    },
    "4PAYLOAD": {
        "action": "activity_stream_event",
        "action_position": 0,
        "addon_version": "1.1.5",
        "client_id": "13a8f957-25aa-b745-b18d-e3b85d816cc1",
        "event": "CLICK",
        "locale": "en-US",
        "page": "NEW_TAB",
        "session_id": "{85ef58f6-17b5-b047-9c78-ed6c59d09470}",
        "shield_variant": "shield-study-01-ActivityStream",
        "source": "TOP_SITES",
        "tab_id": "-3-3"
    },
    "5PING": {
        "action": "activity_stream_event",
        "action_position": 0,
        "addon_version": "1.1.5",
        "client_id": "13a8f957-25aa-b745-b18d-e3b85d816cc1",
        "event": "CLICK",
        "locale": "en-US",
        "page": "NEW_TAB",
        "session_id": "{85ef58f6-17b5-b047-9c78-ed6c59d09470}",
        "shield_variant": "shield-study-01-ActivityStream",
        "source": "TOP_SITES",
        "tab_id": "-3-3"
    },
    "6PING": {
        "action": "activity_stream_session",
        "addon_version": "1.1.5",
        "client_id": "13a8f957-25aa-b745-b18d-e3b85d816cc1",
        "load_latency": 975,
        "load_reason": "newtab",
        "locale": "en-US",
        "page": "NEW_TAB",
        "session_duration": 4863,
        "session_id": "{85ef58f6-17b5-b047-9c78-ed6c59d09470}",
        "tab_id": "-3-3",
        "total_bookmarks": 167,
        "total_history_size": 100015,
        "unload_reason": "click",
        "url": "resource://activity-streams/data/content/activity-streams.html#/"
    },
    "7PAYLOAD": {
        "action": "activity_stream_event",
        "action_position": 0,
        "addon_version": "1.1.5",
        "client_id": "13a8f957-25aa-b745-b18d-e3b85d816cc1",
        "event": "CLICK",
        "highlight_type": "history",
        "locale": "en-US",
        "metadata_source": "TippyTopProvider",
        "page": "NEW_TAB",
        "session_id": "{81051265-e330-5543-9151-c8f492b98bde}",
        "shield_variant": "shield-study-01-ActivityStream",
        "source": "FEATURED",
        "tab_id": "-3-4"
    },
    "8PING": {
        "action": "activity_stream_event",
        "action_position": 0,
        "addon_version": "1.1.5",
        "client_id": "13a8f957-25aa-b745-b18d-e3b85d816cc1",
        "event": "CLICK",
        "highlight_type": "history",
        "locale": "en-US",
        "metadata_source": "TippyTopProvider",
        "page": "NEW_TAB",
        "session_id": "{81051265-e330-5543-9151-c8f492b98bde}",
        "shield_variant": "shield-study-01-ActivityStream",
        "source": "FEATURED",
        "tab_id": "-3-4"
    },
    "9PING": {
        "action": "activity_stream_session",
        "addon_version": "1.1.5",
        "client_id": "13a8f957-25aa-b745-b18d-e3b85d816cc1",
        "load_latency": 913,
        "load_reason": "newtab",
        "locale": "en-US",
        "page": "NEW_TAB",
        "session_duration": 3419,
        "session_id": "{81051265-e330-5543-9151-c8f492b98bde}",
        "tab_id": "-3-4",
        "total_bookmarks": 167,
        "total_history_size": 100016,
        "unload_reason": "click",
        "url": "resource://activity-streams/data/content/activity-streams.html#/"
    }
}
```

**Comment by sarracini** [comment]
cc @k88hudson can you do a sanity check on the yamscript file bit?

File: addon/TelemetrySender.js [hunk 1]
```diff
@@ -63,6 +63,8 @@ TelemetrySender.prototype = {
   },
 
   _sendPing(data) {
+    console.log(`PAYLOAD: ${data}`);
```
Comment (Mardak) [inline addon/TelemetrySender.js]: Just checking, we explicitly want to keep this? You mention it in the documentation, and this is a separate branch anyway.

File: SHIELD.md [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+}
+```
+
+## What we hope to achieve
+
+The success criteria for the SHIELD study is as follows:
+- Increase the average number of top sites clicks per user per day
+- Increase the average number of newtab searches per user per day
+- Increase the average number of newtab sessions per user per day.
+
```
Comment (Mardak) [inline SHIELD.md]: Might want to say that we want to maintain the search volume.

File: SHIELD.md [hunk 3]
```diff
@@ -0,0 +1,68 @@
...
+	"shield_variant":"shield-study-01-Tiles",
+	"action":"activity_stream_event",
+	"tab_id":"-3-2",
+	"client_id":"ee88c4ef-4f1d-8149-9582-b727dc92e89f",
+	"addon_version":"1.1.5",
+	"locale":"en-US",
+	"page":"NEW_TAB",
+	"session_id":"{ab6f3b3e-dfc6-f944-b082-6f4bbbc21e72}"
+}
+```
```
Comment (Mardak) [inline SHIELD.md]: Would be good to include the search ping (to be clear that we aren't sending the query) and the session ping (shows the history and bookmark size, etc).

File: SHIELD.md [hunk 4]
```diff
@@ -0,0 +1,68 @@
...
+
+User eligibility criteria:
+
+- Must have about:newtab enabled
+- Must have local set to en-US
+- Must not have Test Pilot add on installed
+
+Findings: *links to dashboards go here*
+
+###shield-study-02
```
Comment (Mardak) [inline SHIELD.md]: How do we expect to track these in the repository? I suppose we can tag the "release" and just replace the code in `shield.js` for future studies.

File: addon/TabTracker.js [hunk 5]
```diff
@@ -18,10 +18,7 @@ const COMPLETE_NOTIF = "tab-session-complete";
 const ACTION_NOTIF = "user-action-event";
 const PERFORMANCE_NOTIF = "performance-event";
 const PERF_LOG_COMPLETE_NOTIF = "performance-log-complete";
-const DEFAULT_PLACES_QUERIES = {
-  getBookmarksSize() {return Promise.resolve(0);},
-  getHistorySize() {return Promise.resolve(0);}
-};
+
```
Comment (Mardak) [inline addon/TabTracker.js]: Probably want to file an issue to remove this from `master` as well.

File: addon/index.js [hunk 6]
```diff
@@ -0,0 +1,40 @@
...
+  days: 14,
+  variations: {
+    "ActivityStream": () => feature.loadActivityStream(),
+    "Tiles": () => feature.loadTiles()
+  }
+};
+
+class OurStudy extends shield.Study {
+  constructor(config) { // eslint-disable-line no-useless-constructor
+    super(config);
```
Comment (Mardak) [inline addon/index.js]: Any reason not to just remove the constructor and have it automatically delegate?

File: addon/shield.js [hunk 7]
```diff
@@ -0,0 +1,201 @@
...
+
+  doesHaveTestPilot() {
+    const testPilotID = "@testpilot";
+    return getAddonByID(testPilotID).then(addon => {
+      this._doesHaveTestPilot = !!addon;
+    });
+  },
+
+  shutdown(reason, variant) {
+    if (this._activityStreamApp && variant === "ActivityStream") {
```
Comment (Mardak) [inline addon/shield.js]: This might have been a little bit cleaner if there were two `ActivityStreamVariant` and `TilesVariant` that knew how to `load` and `shutdown`. Right now there's a bunch of internal variables and methods that are only used for one or the other. No need to fix here.

File: SHIELD.md (hunk 4 above)
Comment (sarracini) [inline SHIELD.md]: yeah i was thinking it would just have to be tagged manually as we release future studies. we would have to update the shield_variant anyways. We'll have to update this doc periodically to reflect info

File: addon/TelemetrySender.js (hunk 1 above)
Comment (sarracini) [inline addon/TelemetrySender.js]: I'm not sure, I think we should remove it because it'll log to the browser console when we deploy this and i don't know if that's ok

**Comment by Mardak** [comment]
> cc @k88hudson can you do a sanity check on the yamscript file bit?

**Comment by k88hudson** [comment]
@Mardak LGTM
