### PR TITLE
fix(highlights): Heavily boost recent bookmarks and not much from 3 days or older

### LINKED ISSUE #1887: Recently bookmarked pages should show on newtab no mater what, older ones shouldn't
@bryanbell suggests bookmarks made within 3 days get a boost so that just bookmarked pages show up for sure:
```
give a bookmark that’s 0-120minutes old a Plus 100 points
then a bookmark that’s 120-500mins old gets a +40
a bookmark that’s older than 3 days gets no point boost
```

### PR DESCRIPTION
**Pull request by Mardak**
Fix #1887. Instead of a fixed number, base the boost on the age of the bookmark. r?@ncloudioj

### CODE REVIEW

File: common/recommender/Baseline.js [hunk 1]
```diff
@@ -42,13 +42,13 @@ class Baseline {
 
     const age = this.normalizeTimestamp(entry.lastVisitDate);
     const imageCount = entry.images ? entry.images.length : 0;
-    const isBookmarked = !!entry.bookmarkDateCreated;
+    const bookmarkAge = entry.bookmarkDateCreated ? Math.max(1, Date.now() - entry.bookmarkDateCreated) : 0;
```
Comment (ncloudioj) [inline common/recommender/Baseline.js]: For the better readablity, please add a comment for `bookmarkAge`. For example, calculate the age in milliseconds (minimal as 1) if it's a bookmark, otherwise using 0 for non-bookmark links"

File: common/recommender/Baseline.js [hunk 2]
```diff
@@ -104,9 +104,10 @@ class Baseline {
       newScore *= 0.2;
     }
 
-    // Boost boomarks even if they have low score or no images
-    if (features.isBookmarked) {
-      newScore += 1.8;
+    // Boost boomarks even if they have low score or no images giving a
+    // just-bookmarked page a near-infinite boost, and 3-day page 1.0 boost
+    if (features.bookmarkAge) {
+      newScore += 3 * 24 * 60 * 60 * 1000 / features.bookmarkAge;
```
Comment (ncloudioj) [inline common/recommender/Baseline.js]: Consider using a constant here, and update the comment accordingly?

**Comment by ncloudioj** [comment]
This looks good for now.

Since we're adding more and more magic sauce to here, documenting the process of the algorithm evolution is highly recommended :)
