### PR TITLE
fix (content): #2168 update tippy tops.

### LINKED ISSUE #2168: Top Sites: iCloud doesn't have a border
screen shot 2017-02-13 at 2 23 45 pm

There should be a border around the iCloud top site, much like the Amazon tile.

### PR DESCRIPTION
**Pull request by rlr**
* bigger icons
* always show border around them

Fixes #2168

### CODE REVIEW

File: content-src/components/TopSites/TopSites.js [hunk 1]
```diff
@@ -21,14 +21,17 @@ const TopSitesItem = React.createClass({
...
     return {onClick() {}};
   },
+  _isTippyTop(favicon_url) {
+    return favicon_url && (favicon_url.startsWith("favicons/images") || favicon_url.startsWith("resource://"));
+  },
   _faviconSize(site, topSitesExperimentIsOn, screenshot) {
     let faviconSize = 32;
     if (topSitesExperimentIsOn && !screenshot) {
-      if (site.favicon_url && (site.favicon_url.startsWith("favicons/images") || site.favicon_url.startsWith("resource://"))) {
+      if (this._isTippyTop(site.favicon_url)) {
```
Comment (ncloudioj) [inline content-src/components/TopSites/TopSites.js]: nit: can you move the comments below to the `_isTippyTop` function?

**Comment by as-pine-proxy** [comment]
[Treeherder: 55e4d46b336554ec079af123659a0cf21469bc44](https://treeherder.mozilla.org/#/jobs?repo=pine&revision=55e4d46b336554ec079af123659a0cf21469bc44)
