### PR TITLE
fix(crash): Fixes #1567 AS crashes on force shutdown

### LINKED ISSUE #1567: Crash on Nightly when restarting or closing the browser if the Activity Stream add-on is installed
**[Affected versions]:**
-Nightly 52.0a1 (Build ID: 20161016030205)
-Activity Stream 1.1.4-dev

**[Affected Platforms]:**
-All Windows

**[Prerequisites]:**
-Latest Activity Stream add-on version (1.1.4-dev) was previously installed on a clean profile.

**[Steps to reproduce]:**
1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Close/restart the browser from "Option menu"/"Developer toolbar".

[Expected results]:
-Firefox is closed or restarted successfully.

**[Actual results]:**
-The browser crashes.

**[Notes]:**
[Crash report](https://crash-stats.mozilla.com/report/index/f6e506cc-b96b-47de-b9eb-8d2bb2161017)

### PR DESCRIPTION
**Pull request by sarracini**
* Don't assume ```this``` exists - exclusively declare the variable

### CODE REVIEW

File: addon/main.js [hunk 1]
```diff
@@ -92,8 +93,8 @@ Object.assign(exports, {
       app = null;
     }
 
-    if (this.reconnectTimeoutID) {
-      clearTimeout(this.reconnectTimeoutID);
+    if (reconnectTimeoutID) {
+      clearTimeout(reconnectTimeoutID);
```
Comment (ncloudioj) [inline addon/main.js]: nit: set this reconnectTimeoutID to null here, just be safe :)
