### PR TITLE
fix(addon): #2245 - Add user prefs to the session/event/performance pings

### LINKED ISSUE #2245: Track activity stream configuration per session in telemetry
We should add three fields to our session telemetry to track which features a user has enabled in each session:

search_enabled
topsites_enabled
highlights_enabled

This will allow us to figure out what users are seeing in each session.

### PR DESCRIPTION
**Pull request by ncloudioj**
This fixes #2245

### CODE REVIEW

File: addon/TabTracker.js [hunk 1]
```diff
@@ -88,12 +90,24 @@ TabTracker.prototype = {
     };
   },
 
+  _getUserPreferences() {
+    let prefs = 0;
+    USER_PREFS.forEach(item => {
+      if (simplePrefs.prefs[item]) {
+        prefs |= NEWTAB_PREFS_ENCODING[item];
```
Comment (emtwo) [inline addon/TabTracker.js]: great!

File: common/constants.js [hunk 2]
```diff
@@ -26,5 +26,13 @@ module.exports = {
...
   // This is a perf event
-  WORKER_ATTACHED_EVENT: "WORKER_ATTACHED"
+  WORKER_ATTACHED_EVENT: "WORKER_ATTACHED",
+
+  // Newtab preferences encoding
+  NEWTAB_PREFS_ENCODING: {
+    "showSearch": 1 << 0,
+    "showTopSites": 1 << 1,
+    "showHighlights": 1 << 2,
+    "showMoreTopSites": 1 << 3
```
Comment (rlr) [inline common/constants.js]: fancy 👖 !
