### PR TITLE
fix(addon): #760 Add pageshow event to keep track of clicks on the 'back' button.

### LINKED ISSUE #760: Clicking on the "back" button in the browser does not start a new session.
But it should.

### PR DESCRIPTION
**Pull request by emtwo**
Fixes #760 

This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-stream/771)

### CODE REVIEW

File: lib/TabTracker.js [hunk 1]
```diff
@@ -186,6 +189,18 @@ TabTracker.prototype = {
     }
   },
 
+  logPageShow(tab) {
+    // 'pageshow' events are triggered whenever 'ready' events are triggered as well
+    // as whenever a user hits the 'back' button on the browser. The 'ready' event
+    // is emitted before this 'pageshow' event in cases when both are triggered.
+    // Thus, if we get here and load_reason still has not been set, then we know
+    // we got here due to a click of the 'back' button.
```
Comment (k88hudson) [inline lib/TabTracker.js]: 👍

**Comment by k88hudson** [comment]
LGTM 👍
