### PR TITLE
fix(mc): #2917 Only initialize search on focus

### LINKED ISSUE #2917: Delay loading of content search until necessary
From mconley's joy of coding 106 notes:

https://www.evernote.com/shard/s434/sh/4cc743c4-933f-4917-af1e-343acf32a096/eb0c9f60ac08f6f0
> Leaking Blob URI:
contentSearchUI probably leaks Blob URIs if the favicons for the one-off buttons are never shown (like, if the defaultEngine is set, but the user never tries to do a search in about:newtab).

### PR DESCRIPTION
**Pull request by k88hudson**
Fix #2917.

### CODE REVIEW

File: system-addon/content-src/components/Search/Search.jsx [hunk 1]
```diff
@@ -8,33 +8,43 @@ const {actionCreators: ac} = require("common/Actions.jsm");
...
-    }
+  onFocus(e) {
+    this.initializeSearch();
+  }
+  componentDidMount() {
+    // The first "newtab" parameter here is called the "healthReportKey" and needs
+    // to be "newtab" so that BrowserUsageTelemetry.jsm knows to handle events with
+    // this name, and can add the appropriate telemetry probes for search. Without the
+    // correct name, certain tests like browser_UsageTelemetry_content.js will fail (See
+    // github ticket #2348 for more details)
```
Comment (Mardak) [inline system-addon/content-src/components/Search/Search.jsx]: This comment block should go next to the `new ContentSearchUIController` in `initializeSearch`

File: system-addon/content-src/components/Search/Search.jsx [hunk 2]
```diff
@@ -49,10 +59,11 @@ class Search extends React.Component {
       </label>
       <input
         id="newtab-search-text"
+        ref={input => { this.input = input; }}
```
Comment (Mardak) [inline system-addon/content-src/components/Search/Search.jsx]: We don't want `bind` in `render`. Can't this be a string to access via `refs`?

File: system-addon/content-src/components/Search/Search.jsx [hunk 3]
```diff
@@ -49,10 +59,11 @@ class Search extends React.Component {
...
         maxLength="256"
         placeholder={this.props.intl.formatMessage({id: "search_web_placeholder"})}
-        ref={this.onInputMount}
         title={this.props.intl.formatMessage({id: "search_web_placeholder"})}
+        onFocus={this.controller ? null : this.onFocus}
```
Comment (Mardak) [inline system-addon/content-src/components/Search/Search.jsx]: Will we ever `render` when `controller` already exists? Seems like `onFocus` will be called on focus each time anyway and there's guards to prevent reinitializing.

File: system-addon/content-src/components/Search/Search.jsx [hunk 4]
```diff
@@ -8,33 +8,43 @@ const {actionCreators: ac} = require("common/Actions.jsm");
...
+    if (this.controller) {
+      return;
+    }
+    this.controller = new ContentSearchUIController(this.input, this.input.parentNode,
+      "newtab", "newtab");
+  }
   onClick(event) {
+    if (!this.controller) {
+      this.initializeSearch();
+    }
```
Comment (Mardak) [inline system-addon/content-src/components/Search/Search.jsx]: I'm suspicious if this works as async messages take time to happen ? Although maybe the controller is smart enough to delay its `search`? Also, I suppose it's safe to check if `controller` exists but `initializeSearch` does it too. ;) Whatever you think is clearer.

File: system-addon/content-src/components/Search/Search.jsx (hunk 2 above)
Comment (k88hudson) [inline system-addon/content-src/components/Search/Search.jsx]: String refs are considered legacy, although i could add this function to the class definition to avoid re-binding it

File: system-addon/content-src/components/Search/Search.jsx (hunk 3 above)
Comment (k88hudson) [inline system-addon/content-src/components/Search/Search.jsx]: oh yeah good point.

File: system-addon/content-src/components/Search/Search.jsx [hunk 5]
```diff
@@ -49,10 +61,11 @@ class Search extends React.Component {
       </label>
       <input
         id="newtab-search-text"
+        ref={this.onInputMount}
         maxLength="256"
         placeholder={this.props.intl.formatMessage({id: "search_web_placeholder"})}
-        ref={this.onInputMount}
         title={this.props.intl.formatMessage({id: "search_web_placeholder"})}
+        onFocus={this.onFocus}
```
Comment (Mardak) [inline system-addon/content-src/components/Search/Search.jsx]: but but alphabetical! oh well… ;)

**Comment by as-pine-proxy** [comment]
[Treeherder: eb86619eca3a5ccd1bfbf5dbd2977dccaa9caaa6](https://treeherder.mozilla.org/#/jobs?repo=pine&revision=eb86619eca3a5ccd1bfbf5dbd2977dccaa9caaa6)
