### PR TITLE
fix (addon): #1034 Fix event ping to include experiment data only if necessary

### LINKED ISSUE #1034: Clicks counts on highlights look incorrect
When running the query below we see a drastic drop in clicks on highlights on July 28th, which is when we released the new recommendation.

This is likely a bug in the code for collecting this data. I would expect a pretty small drop if people are clicking on recommendations more but this drop looks too big.

```
SELECT date, COUNT(*)
FROM activity_stream_events_daily
WHERE event IN ('CLICK', 'click')
AND source = 'FEATURED'
AND date >= '07/15/16'
AND (recommendation_url IS NULL
     OR recommendation_url = 'n/a')
GROUP BY date
ORDER BY date
```

### PR DESCRIPTION
**Pull request by ncloudioj**
This fixes #1034

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-stream/1036)

### CODE REVIEW

File: lib/RecommendationProvider.js [hunk 1]
```diff
@@ -48,13 +48,13 @@ RecommendationProvider.prototype = {
...
-    this._tabTracker.handleUserEvent({
-      event: "NEW_RECOMMENDATION",
-      url: url,
-      recommender_type: recommenderType
-    });
+    if (currentRecommendation && currentRecommendation.url &&
+      currentRecommendation.recommender_type) {
+      let payload = {event: "NEW_RECOMMENDATION"};
+      payload.url = currentRecommendation.url;
+      payload.recommender_type = currentRecommendation.recommender_type;
```
Comment (emtwo) [inline lib/RecommendationProvider.js]: nit: is there a reason `url` and `recommender_type` are not part of the `payload` object when you first generate it? I think it should be safe to do that since you added that if statement right?

**Comment by emtwo** [comment]
r+ aside from minor nit. Thanks Nan!

File: lib/RecommendationProvider.js (hunk 1 above)
Comment (ncloudioj) [inline lib/RecommendationProvider.js]: In the unit test [here](https://github.com/mozilla/activity-stream/blob/master/test/test-RecommendationProvider.js#L88), there is a special case where the `currentRecommendation` is `null`. So I guess if the `currentRecommendation` is null, we shuoldn't send out a ping with both "url" and "recommender_type" as null.

Does it make sense?

Comment (ncloudioj) [inline lib/RecommendationProvider.js]: I meant, just wanted to make sure both two fields are valid before send the ping out.

**Comment by ncloudioj** [comment]
Thanks for pointing that out! @emtwo 👍
