### PR TITLE
fix (content): #1298 stop propagation on "Share" click event

### LINKED ISSUE #1298: The context menu is dismissed if you click on the "Share" option
via https://bugzilla.mozilla.org/show_bug.cgi?id=1303022
<hr>

[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.1.3-dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.1.3-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Open the context menu for Top Sites, Highlights or Recent Activity.
3. Hover and then click the "Share" option.

[Expected result]:
- Nothing happens.

[Actual result]:
- The context menu is dismissed.

[Additional Notes]:
- Attached a screen recording of the issue https://goo.gl/zFqkil.

### PR DESCRIPTION
**Pull request by rlr**
tiny r? @k88hudson 

Fixes #1298

### CODE REVIEW

File: content-src/components/ContextMenu/ContextMenu.js [hunk 1]
```diff
@@ -28,7 +28,10 @@ const ContextMenu = React.createClass({
             return (<li key={i}><div
               className="submenu"
               ref={option.ref}
-              onClick={() => {}}>
+              onClick={ev => {
+                ev.stopPropagation();
+                return false;
```
Comment (k88hudson) [inline content-src/components/ContextMenu/ContextMenu.js]: this is not neccesssary as of current web standards

Comment (rlr) [inline content-src/components/ContextMenu/ContextMenu.js]: bad habits die slowly 😬
