### PR TITLE
Refactor selectors to fix dedupe bug

### LINKED ISSUE #1284: Highlights missing on new tab page
Weighted highlights showing less than 3 results. We determined the issue and working on a fix.
Should only affect new profiles.

missing highlights

### PR DESCRIPTION
**Pull request by piatra**
Fixed #1284

### CODE REVIEW

File: content-src/selectors/selectors.js [hunk 1]
```diff
@@ -16,18 +16,32 @@ function isValidSpotlightSite(site) {
     site.title !== site.description);
 }
 
+/**
+ * Dedupe items and appends defaults if result length is smaller than required.
+ *
+ * @param {Array} options.sites - sites to process.
+ * @param {Array} options.dedupe - sites to dedupe against.
+ * @param {Array} options.max - required number of items.
```
Comment (k88hudson) [inline content-src/selectors/selectors.js]: this is a `Number`, not an array

File: content-src/selectors/selectors.js [hunk 2]
```diff
@@ -5,7 +5,7 @@ const {assignImageAndBackgroundColor} = require("selectors/colorSelectors");
 
 const SPOTLIGHT_LENGTH = module.exports.SPOTLIGHT_LENGTH = 3;
 const TOP_SITES_LENGTH = module.exports.TOP_SITES_LENGTH = 6;
-const MIN_HIGHLIGHTS_LENGTH = module.exports.MIN_HIGHLIGHTS_LENGTH = 5;
+const HIGHLIGHTS_LENGTH = module.exports.HIGHLIGHTS_LENGTH = 12;
```
Comment (k88hudson) [inline content-src/selectors/selectors.js]: I know this seems super redundant, can we call this `BOTTOM_HIGHLIGHTS_LENGTH` and add another line that says 
```
const TOP_HIGHLIGHTS_LENGTH = SPOTLIGHT_LENGTH;
```

File: content-src/selectors/selectors.js [hunk 3]
```diff
@@ -106,9 +120,12 @@ module.exports.selectNewTabSites = createSelector(
 
     let topHighlights = spotlightRows;
     if (prefWeightedHighlights) {
-      topHighlights = dedupe.group([
-        topSitesRows,
-        WeightedHighlights.rows])[1];
+      topHighlights = selectAndDedupe({
+        dedupe: topSitesRows,
+        sites: WeightedHighlights.rows,
+        max: HIGHLIGHTS_LENGTH + SPOTLIGHT_LENGTH,
```
Comment (k88hudson) [inline content-src/selectors/selectors.js]: so here would be `TOP_HIGHLIGHTS_LENGTH + BOTTOM_HIGHLIGHTS_LENGTH`

File: content-test/selectors/selectors.test.js [hunk 4]
```diff
@@ -278,20 +279,39 @@ describe("selectors", () => {
...
+    });
+    it("should append defaults if result length is under the specified limit", () => {
+      const result = selectAndDedupe({
+        sites: ["http://www.mozilla.org"],
+        dedupe: [],
+        max: 5,
+        defaults: firstRunData.Highlights
+      });
+
+      assert.equal(result.length, 1 + firstRunData.Highlights.length);
```
Comment (k88hudson) [inline content-test/selectors/selectors.test.js]: since `selectAndDedupe` should still only return a max of `options.max`, can we test a case where the combined length of `options.sites` and `options.defaults` is greater than the max?

File: content-src/selectors/selectors.js (hunk 2 above)
Comment (piatra) [inline content-src/selectors/selectors.js]: 👍

**Comment by piatra** [comment]
Updated. Please review @k88hudson .

**Comment by k88hudson** [comment]
@piatra 👍
