### PR TITLE
fix (animations): #3707 only animate when page is visible

### LINKED ISSUE #3707: Collapsed sections are animated again when switching to a previous opened New Tab
https://bugzilla.mozilla.org/show_bug.cgi?id=1408407

[Affected versions]:
- Firefox 58.0a1 Build ID 20171012220111

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and open two New Tabs.
2. Collapse the Top Sites section.
3. Switch to the other New Tab and observed the collapsed section.

[Expected results]:
- The section is collapsed.

[Actual results]:
- The section is collapses when the tab is focused.

[Notes]:
- The issue is not reproducible if the section is opened in one tab and then you switch to another new tab.
- The issue is also reproducible in a new opened tab, but you have to open a new tab right after collapsing a section. 
- The issue is also reproducible with the Highlights and Recommended by Pocket sections.
- Attached a screen recording of the issue:
collapsed section is animated again when switching to a different new tab

### PR DESCRIPTION
**Pull request by rlr**
The issue was that animations/transitions in background tabs are aggressively throttled or paused. So once the tab is brought into view, the rest of the animation happens. To fix, I just disabled the transitions for non visible tabs.

Fixes #3707

### CODE REVIEW

File: system-addon/content-src/components/CollapsibleSection/CollapsibleSection.jsx [hunk 1]
```diff
@@ -155,7 +174,14 @@ class CollapsibleSection extends React.PureComponent {
   }
 }
 
-CollapsibleSection.defaultProps = {Prefs: {values: {}}};
+CollapsibleSection.defaultProps = {
+  document: global.document || {
+    addEventListener: () => {},
+    removeEventListener: () => {},
+    visibilityState: "prerender"
```
Comment (rlr) [inline system-addon/content-src/components/CollapsibleSection/CollapsibleSection.jsx]: @sarracini fixed it with this. Seem reasonable?

Comment (rlr) [reply system-addon/content-src/components/CollapsibleSection/CollapsibleSection.jsx]: https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilityState

**Comment by Mardak** [comment]
Might be a good time to refactor `visibilitychange` stuff. There will be 4 places doing the similar visibility checks with this change. Also, at least for prerendered pages, the value is "hidden" -- I don't think Firefox actually does "prerender" state ? ?

**Comment by Mardak** [comment]
I haven't looked closely at how other places are using visibility, but for this fix, we could probably set some `body.shouldAnimate` class to turn off animations.. maybe? Could be then reused for #3698.

**Comment by rlr** [comment]
@Mardak the other checks for `visibilityState` are a little different than this case. Those seem to only want to listen for a change if the page isn't visible initially, where in this case we are constantly toggling animations as visibility changes. And I'm not sure what we could do to refactor other than create a facade on top of the DOM API.  I don't think we want to add it to the redux store?

I'm not sure about `body.shouldAnimate` since `<body/>` is outside of what redux controls, but having the logic in `Base.jsx` might be a good idea if we want a switch to disable all animations on the page. We would have to wrap all the transition/animation styles in an extra class. Maybe put them all in a separate _animations.scss file too.

**Comment by Mardak** [comment]
> I don't think we want to add it to the redux store?

@k88hudson any suggestions on how to share watching for "visibilitychange" and getting `document.visibilityState`. I suppose the DOM APIs are quite simple enough, so anything we do could just be unnecessary wrapper… I.e., whatever we end up with might just be almost the same as what we would be doing with the multiple `addEventListener`s.

**Comment by Mardak** [comment]
I suppose the thing that's bothering me is we end up defining the same `const` 3 places ;)

`const VISIBILITY_CHANGE_EVENT = "visibilitychange";`

But I suppose that's not really that different from all 4 places just using "visibilitychange" inline or `something.shared.onVisibilityChange`

File: system-addon/content-src/components/CollapsibleSection/CollapsibleSection.jsx [hunk 2]
```diff
@@ -93,7 +96,23 @@ class CollapsibleSection extends React.PureComponent {
     this.onInfoLeave = this.onInfoLeave.bind(this);
     this.onHeaderClick = this.onHeaderClick.bind(this);
     this.onTransitionEnd = this.onTransitionEnd.bind(this);
-    this.state = {isAnimating: false, infoActive: false};
+    this.enableOrDisableAnimation = this.enableOrDisableAnimation.bind(this);
+    this.state = {enableAnimation: false, isAnimating: false, infoActive: false};
+  }
+
+  componentWillMount() {
+    this.enableOrDisableAnimation();
```
Comment (sarracini) [inline system-addon/content-src/components/CollapsibleSection/CollapsibleSection.jsx]: Do you need this initial call to ```enableOrDisableAnimation()```? I removed it and it seemed to work the same since the function is called anyways when you open a new tab because of the event listener firing

Comment (sarracini) [reply system-addon/content-src/components/CollapsibleSection/CollapsibleSection.jsx]: I guess to be safe that all visible tabs start with ```animation-enabled``` you could set ```enableAnimation : true``` in the constructor

File: system-addon/content-src/components/CollapsibleSection/CollapsibleSection.jsx (hunk 1 above)
Comment (sarracini) [reply system-addon/content-src/components/CollapsibleSection/CollapsibleSection.jsx]: Yup this seems good!

File: system-addon/content-src/components/CollapsibleSection/CollapsibleSection.jsx (hunk 2 above)
Comment (rlr) [reply system-addon/content-src/components/CollapsibleSection/CollapsibleSection.jsx]: I *think* we need to call `enableOrDisableAnimation()` on mount in case it is initially a non-visilble tab that is loading. Or does that still trigger a "visibilitychange" event? I'll play with it a little.

Comment (rlr) [reply system-addon/content-src/components/CollapsibleSection/CollapsibleSection.jsx]: Actually, you're right. It doesn't seem to be needed 👍

**Comment by as-pine-proxy** [comment]
[Treeherder: b5750842888acad5d853e49176a5fed40c3364d2](https://treeherder.mozilla.org/#/jobs?repo=pine&revision=b5750842888acad5d853e49176a5fed40c3364d2)
