### PR TITLE
fix(metadatastore): #1577: Add parameterized query

### LINKED ISSUE #1577: Images are missing from Highlights
**[Affected versions]:**
-Nightly 45 and up
-Activity Stream 1.1.4-dev

**[Affected Platforms]:**
-All Windows

**[Prerequisites]:**
-Latest Activity Stream add-on version (1.1.4-dev) was previously installed on a profile with browsing history.

**[Steps to reproduce]:**
1. Start the browser with the profile from prerequisites.
2. Open a new tab and observe the Highlights from New Tab page.

**[Expected results]:**
-Spotlight image is displayed for items that are in Highlights tiles.

**[Actual results]:**
-The spotlight image is not displayed for Highlights, only the favicon is displayed.

**[Notes]:**
-Attached a screenshot of the issue:
highlights without spotlight image

### PR DESCRIPTION
**Pull request by ncloudioj**
This fixes #1577 as well as following issues that we've encountered before:
* failure of fetching metadata if there are special characters in the `cache_key`
* `unique constraint violation` due to the similar bug in the "asyncCacheKeyExists"

More importantly, it prevents metadata store from the potential SQL injection hazard.

### CODE REVIEW

File: test/test-MetadataStore.js [hunk 1]
```diff
@@ -183,6 +183,45 @@ exports.test_async_get_single_link_by_cache_key = function*(assert) {
   assert.equal(linkExists, false, "It should return an empty array since it doesn't exist");
 };
 
+function _makeFunkyMetadataFixture() {
+  // Deep copy the metadata fixture
+  let funkyFixture = metadataFixture.map(fixture => Object.assign({}, fixture));
+  let fixture = funkyFixture[0];
+  fixture.cache_key = "I'm funky";
```
Comment (rlr) [inline test/test-MetadataStore.js]: haha! nice

File: addon/MetadataStore.js [hunk 2]
```diff
@@ -425,25 +425,28 @@ MetadataStore.prototype = {
...
    *
    * Returns a promise with the array of retrieved metadata records
    */
   asyncGetMetadataByCacheKey: Task.async(function*(cacheKeys) {
-    const quoted = cacheKeys.map(key => `'${key}'`).join(",");
+    const quoted = cacheKeys.map(key => "?").join(",");
     let metaObjects;
     try {
       metaObjects = yield this.asyncExecuteQuery(
         `SELECT * FROM page_metadata WHERE cache_key IN (${quoted})`,
```
Comment (rlr) [inline addon/MetadataStore.js]: I'm pretty sure you could've done just `:keys` then `params: {keys: cacheKeys}` below. Kind of like you did the other query. Did you try that?

Comment (ncloudioj) [inline addon/MetadataStore.js]: I've tried doing in that way, but it didn't work out. Looks like for the `SELECT .. IN ()` statements, you need to build that placeholders `(?, ?, ?)` dynamically.

**Comment by ncloudioj** [comment]
A huge thanks to y'all for figuring this out @rlr and @k88hudson.
I dug this hole here, let me fill it up 😜

**Comment by k88hudson** [comment]
It's all good @ncloudioj! Thanks for fixing so quickly 👍
