### PR TITLE
Fix(addon): #1620 - Update experimentId for TabTracker upon changes

### LINKED ISSUE #1620: Tab tracker doesn't update experiment_id if it changes after initialization

### PR DESCRIPTION
**Pull request by ncloudioj**
This closes #1620

### CODE REVIEW

File: addon/TabTracker.js [hunk 1]
```diff
@@ -94,6 +94,10 @@ TabTracker.prototype = {
     }
   },
 
+  set experimentId(exprimentID) {
```
Comment (k88hudson) [inline addon/TabTracker.js]: typo: `exprimentID`
