### PR TITLE
fix(addon): #2210 - Add telemetry for screenshots expriment

### LINKED ISSUE #2210: Collect screenshots experiment data
Including:
* Number of screenshots shown in a session
* Whether a clicked topsite had a screenshot (I believe we have this already, but need to confirm)

### PR DESCRIPTION
**Pull request by ncloudioj**
This fixes #2210

### CODE REVIEW

File: addon/TabTracker.js [hunk 1]
```diff
@@ -178,24 +178,45 @@ TabTracker.prototype = {
     // unload_reason could be set in "handleUserEvent" for certain user events
     // in order to provide the more sepcific reasons other than "navigation"
     this._tabData.unload_reason = this._tabData.unload_reason || reason;
+    // caculate the session duration bofore the following bookkeeping computations
```
Comment (rlr) [inline addon/TabTracker.js]: nit: typo "caculate" and "bofore"
