### PR TITLE
fix (content): #1763 fix context menu button clicking

### LINKED ISSUE #1763: Clicking on a context menu button does not close context menu
If you click on the context menu button above a top site or a highlight, it will bring up the context menu, but then clicking the button again does not dismiss it.  Should we consider changing that so clicking the context menu button closes the menu as well?

### PR DESCRIPTION
**Pull request by rlr**
Breaking out `TopSitesItem` into a separate component like we do for Spotlights fixed the issue.

r? @sarracini 

Fixes #1763

### CODE REVIEW

File: content-src/components/LinkMenuButton/LinkMenuButton.js [hunk 1]
```diff
@@ -4,7 +4,6 @@ const LinkMenuButton = React.createClass({
   render() {
     return (<button className="link-menu-button" onClick={e => {
       e.preventDefault();
-      e.stopPropagation();
```
Comment (sarracini) [inline content-src/components/LinkMenuButton/LinkMenuButton.js]: we should revert the changes here https://github.com/mozilla/activity-stream/pull/1748/files#diff-bea2b5a6e0bdde5d8bb69333c83d78e4 if we remove the stopPropogation here. Or else we get the bug #1372

File: content-src/components/TopSites/TopSites.js [hunk 2]
```diff
@@ -11,6 +11,41 @@ const Hint = require("components/Hint/Hint");
...
 
+const TopSitesItem = React.createClass({
+  getInitialState() {
+    return {showContextMenu: false};
+  },
+  getDefaultProps() {
+    return {onClick() {}};
+  },
+  render() {
+    const site = this.props;
```
Comment (sarracini) [inline content-src/components/TopSites/TopSites.js]: nit: unpack index from props here, since you're using it multiple times

File: content-src/components/TopSites/TopSites.js [hunk 3]
```diff
@@ -25,40 +60,37 @@ const TopSites = React.createClass({
...
+  onClickFactory(index, site) {
+    return () => {
+      let payload = {
+        event: "CLICK",
+        page: this.props.page,
+        source: "TOP_SITES",
+        action_position: index,
+        metadata_source: site.metadata_source
+      };
+      if (site.recommended) {
```
Comment (sarracini) [inline content-src/components/TopSites/TopSites.js]: you can remove this recommendation stuff - top sites will never have a recommendation and also we removed the recommendation logic so this can go. (lines 72-79)

File: content-src/components/LinkMenuButton/LinkMenuButton.js (hunk 1 above)
Comment (rlr) [inline content-src/components/LinkMenuButton/LinkMenuButton.js]: ah. great catch!

**Comment by rlr** [comment]
@sarracini i pushed all the fixes from r? ^^
