### PR TITLE
fix(search): #1795 Listen to browser.search.hiddenOneOffs

### LINKED ISSUE #1795: Listen to changes on `browser.search.hiddenOneOffs`
In order to update the selected search choices, let's listen to the following pref:
 https://dxr.mozilla.org/mozilla-central/source/browser/components/preferences/in-content/search.js#292-300

See https://github.com/mozilla/activity-stream/pull/1776 for further notes

### PR DESCRIPTION
**Pull request by k88hudson**
Fix #1795. This patch triggers an event when the `browser.search.hiddenOneOffs` changes, which `SearchFeed` already listens to.

### CODE REVIEW

File: addon/SearchProvider.js [hunk 1]
```diff
@@ -41,6 +44,13 @@ SearchProvider.prototype = {
   ]),
 
   /**
+   * Event listener for the HIDDEN_ENGINES_PREF pref change
+   */
+  _onPrefChange(e) {
+    this.emit(SEARCH_ENGINE_TOPIC, "hiddenOneOffs");
```
Comment (Mardak) [inline addon/SearchProvider.js]: `SearchFeed` happens to just update its list of engines when it eventually gets the action broadcasted by `ActivityStreams`. But this is somewhat dangerous as the same action might have `data` of the string or the engine.
