### PR TITLE
fix(metadata): Closes #1278 Fix YouTube Top Sites icon

### LINKED ISSUE #1278: YouTube Top Sites Icon is 😔
image 2016-09-13 at 9 19 25 am

The YouTube icon doesn't look very good. That top site links to `http://www.youtube.com/`. It seems like it should be the nicer icon from Tippy Top sites.

### PR DESCRIPTION
**Pull request by sarracini**
- Ensures we _always_ add tippytop data if we have it 
- As a result the youtube icon is nice
- Update the tests

@jaredkerim r?

### CODE REVIEW

File: test/test-PreviewProvider.js [hunk 1]
```diff
@@ -303,7 +303,58 @@ exports.test_no_metadata_source = function*(assert) {
...
+    response.write(JSON.stringify(fakeResponse));
+  });
+  // insert a link with some less nice icons in it and get them back
+  yield gPreviewProvider._asyncSaveLinks([fakeSite]);
+  cachedLink = yield gPreviewProvider._asyncGetEnhancedLinks([fakeSite]);
+  tippyTopFavicon = cachedLink[0].favicon_url;
+  tippyTopBackgroundColor = cachedLink[0].background_color;
+
+  assert.equal(tippyTopLink.favicon_url, tippyTopFavicon, "we still took the better tippyTop favicon_url");
+  assert.equal(tippyTopLink.background_color, tippyTopBackgroundColor, "we still took the better tippyTop background_color");
```
Comment (jaredkerim) [inline test/test-PreviewProvider.js]: Can we add an assertion to test that the link object we get back has both the fakeResponse metadata *and* the tippy top data?  If we only check the tippy top fields, we could remove line 351 and this would still pass.

File: test/test-PreviewProvider.js [hunk 2]
```diff
@@ -387,11 +438,15 @@ before(exports, () => {
     },
     asyncGetMetadataByCacheKey(cacheKeys) {
```
Comment (jaredkerim) [inline test/test-PreviewProvider.js]: If this method isn't called anybody we should remove it.

File: addon/PreviewProvider.js [hunk 3]
```diff
@@ -209,16 +209,18 @@ PreviewProvider.prototype = {
...
-
-      if (site) {
-        // Find the item in the map and return it if it exists
-        if (existingLinks.has(site.cache_key)) {
-          enhancedLink = Object.assign({}, existingLinks.get(site.cache_key), site);
-        } else {
-          // Add tippy top data, if available
-          enhancedLink = this._tippyTopProvider.processSite(site);
-        }
+      if (!site) {
```
Comment (jaredkerim) [inline addon/PreviewProvider.js]: If you move this one line up, you can get rid of 

    let enhancedLink = null;

altogether and just add a let to line 215.

**Comment by jaredkerim** [comment]
R+ with test changes and nits.
