### PR TITLE
fix(addon): #759 Add session_id for all pings.

### LINKED ISSUE #759: Event and session pings should have session_id
We should add this because it will make joins between the two tables a lot simpler for finding out what events happened during what sessions.

### PR DESCRIPTION
**Pull request by emtwo**
Fixes #759 

---

This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-stream/780)

### CODE REVIEW

File: lib/TabTracker.js [hunk 1]
```diff
@@ -164,8 +173,6 @@ TabTracker.prototype = {
     // already ended, likely with an 'unfocus' unload reason.
     if (this.isActivityStreamsURL(tab.url) && tabs.activeTab.id === tab.id) {
       if (!this._tabData.url) {
-        this._tabData.url = tab.url;
-        this._tabData.tab_id = tab.id;
```
Comment (emtwo) [inline lib/TabTracker.js]: I removed these two since `logActivate()` will be called a few lines down and it already sets them

File: test/test-TabTracker.js [hunk 2]
```diff
@@ -348,7 +348,7 @@ exports.test_TabTracker_action_pings = function*(assert) {
       data: {
         source: "topsites",
         action_position: 3,
-        event: "click"
+        event: "CLICK"
```
Comment (emtwo) [inline test/test-TabTracker.js]: `handleUserEvent()` is specifically looking for uppercase `CLICK`

File: test/test-TabTracker.js [hunk 3]
```diff
@@ -359,13 +359,29 @@ exports.test_TabTracker_action_pings = function*(assert) {
   for (let key of additionalKeys) {
     assert.ok(pingData[key], `The ping has the additional key ${key}`);
   }
-  assert.deepEqual(eventData.msg.data, pingData, "We receive the expected ping data.");
+  assert.deepEqual(eventData.msg.data.source, pingData.source, "the ping has the correct source");
+  assert.deepEqual(eventData.msg.data.event, pingData.event, "the ping has the correct event");
+  assert.deepEqual(eventData.msg.data.action_position, pingData.action_position, "the ping has the correct action_position");
 };
 
 exports.test_TabTracker_unload_reason_with_user_action = function*(assert) {
```
Comment (emtwo) [inline test/test-TabTracker.js]: In this test, I added promises to wait for tab open and close. This is because `session_id` will only be set after a tab is open (and we must close tabs at the end of every test).

File: test/test-TabTracker.js [hunk 4]
```diff
@@ -359,13 +359,29 @@ exports.test_TabTracker_action_pings = function*(assert) {
   for (let key of additionalKeys) {
     assert.ok(pingData[key], `The ping has the additional key ${key}`);
   }
-  assert.deepEqual(eventData.msg.data, pingData, "We receive the expected ping data.");
+  assert.deepEqual(eventData.msg.data.source, pingData.source, "the ping has the correct source");
+  assert.deepEqual(eventData.msg.data.event, pingData.event, "the ping has the correct event");
+  assert.deepEqual(eventData.msg.data.action_position, pingData.action_position, "the ping has the correct action_position");
```
Comment (emtwo) [inline test/test-TabTracker.js]: Since this test doesn't open a new tab, `session_id` will be set to `undefined`. Thus, we only check the other attributes instead of all

**Comment by emtwo** [comment]
r? @ncloudioj or @k88hudson 

I just left some github notes in the code which should hopefully make it easier to follow.

**Comment by k88hudson** [comment]
Looks good to me! R+

**Comment by ncloudioj** [comment]
r+ @emtwo 🚢
