### PR TITLE
fix(content): #829 fix deprecation warning for frame-src CSP directive

### LINKED ISSUE #829: Content Security Policy: Directive 'frame-src' has been deprecated. Please use directive 'child-src' instead
I'm getting this warning locally when running `$ npm run once` against master (v1.0.19):

> _"Content Security Policy: Directive 'frame-src' has been deprecated. Please use directive 'child-src' instead."_

Per https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives#frame-src:

> _"Note: This directive is deprecated. Use `child-src` instead, unless you are supporting browsers that use CSP 1.0 only (e.g. Safari 9)."_

---

Looks like it's coming from [/bin/generate-html.js:12](https://github.com/mozilla/activity-stream/blob/be02057fb6a415c5395bcabfd26e3df1ea2acdb5/bin/generate-html.js#L12):

```html
<meta http-equiv="Content-Security-Policy"
    content="default-src 'none';
        script-src 'self';
        img-src http: https: data:;
        style-src 'self' 'unsafe-inline';
        child-src 'self' https://*.youtube.com https://*.vimeo.com;
        frame-src 'self' https://*.youtube.com https://*.vimeo.com">
```

activity_stream

### PR DESCRIPTION
**Pull request by oyiptong**
Closes #829 
r? @rlr: I think you were the one to implement the CSP originally

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-stream/942)

### CODE REVIEW

File: bin/generate-html.js [hunk 1]
```diff
@@ -9,7 +9,7 @@ const defaults = {
 function template(rawOptions) {
   const options = Object.assign({}, defaults, rawOptions || {});
   const csp = options.csp === "on" ?
-    "<meta http-equiv=\"Content-Security-Policy\" content=\"default-src 'none'; script-src 'self'; img-src http: https: data:; style-src 'self' 'unsafe-inline'; child-src 'self' https://*.youtube.com https://*.vimeo.com; frame-src 'self' https://*.youtube.com https://*.vimeo.com\">" :
```
Comment (rlr) [inline bin/generate-html.js]: oh, we already had `child-src`. nice.

**Comment by rlr** [comment]
I gave it a try and youtube previews still work. R+!
