### PR TITLE
chore(tests): fixes #2257; fix test-merges for bootstrapped add-on

### LINKED ISSUE #2257: get mochitest test-merges.js working again manually
After #2221, we're going to need a slightly different strategy to use pine, possibly pushing an extra patch commit to cause pine to enable the add-on and run the mochitests.

### PR DESCRIPTION
**Pull request by dmose**
See test-merges.md for the details.  This just ports to make it work with the bootstrapped add-on instead of the SDK add-on. Fix #2257.

### CODE REVIEW

File: bin/prepare-mochitests-dev [hunk 1]
```diff
@@ -17,17 +38,31 @@ if [ $? -ne 0 ]; then
   exit -1
 fi
 
-# Clean, package, and copy the activity stream files, default SYMLINK_TESTS to
-# true but allowing the environment to override so that calling scripts like
-# test-merges.js can export real files in order to have hg add them correctly
-# during the export phase.
+# blow away any old bits in order to workaround bug 1335976 for users
+# who are using the default objdir-frontend
+rm -f ${FIREFOX_PATH}/objdir-frontend/dist/bin/browser/features/@activity-streams/*
```
Comment (Mardak) [inline bin/prepare-mochitests-dev]: This shouldn't really be needed going forwards as `moz.build` for the `system-addon` export does not include any directories as part of `FINAL_TARGET_FILES` but this does help for now.

File: bin/test-merges.js [hunk 2]
```diff
@@ -43,14 +43,22 @@ const TREEHERDER_PREFIX = "https://treeherder.mozilla.org/#/jobs?repo=pine&revis
...
-const TESTING_GIT_AS = path.join(WORKING_DIR, AS_REPO_NAME);
-const git = new SimpleGit(TESTING_GIT_AS);
+const TESTING_LOCAL_GIT = path.join(AS_PINE_TEST_DIR, AS_REPO_NAME);
+const git = new SimpleGit(TESTING_LOCAL_GIT);
+
+// Mostly useful to specify during development of the test automation so that
+// prepare-mochitests-dev and friends from the development repo get used
+// instead of from the testing repo, which won't have had any changes checked in
+// just yet.
+const AS_PMD_GIT_DIR = process.env.AS_PMD_GIT_DIR || TESTING_LOCAL_GIT;
```
Comment (Mardak) [inline bin/test-merges.js]: Nice. I was needing to copy over files and stash them away to avoid them from preventing changes by `git`.

**Comment by as-pine-proxy** [comment]
[Treeherder: 3a34a7b19863b52a52e44ce8e136f4c370787632](https://treeherder.mozilla.org/#/jobs?repo=pine&revision=3a34a7b19863b52a52e44ce8e136f4c370787632)
