### PR TITLE
fix(search): Fixes #1900 Search suggestions not being displayed

### LINKED ISSUE #1900: [Search Bar] Search suggestions are no longer displayed after typing a keyword
[Affected versions]:
- Nightly 53.0a1, Build ID 	20161227030213
- Activity Stream 1.1.8-dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.1.8-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites.
2. Open a new tab and write something in the AS search bar.
3. Observe the Search Suggestions dropdown.

[Expected results]:
- Search suggestions are displayed in the dropdown.

[Actual results]:
- No search suggestions are displayed.

[Notes]:
- The issue is caused by a fix in Nightly:
Last good revision: 0703ad673049694f3ac43744812ed39818678d21
First bad revision: 02514bc7bc54bb207d6e9aab664368968ed15c90
Pushlog:
https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=0703ad673049694f3ac43744812ed39818678d21&tochange=02514bc7bc54bb207d6e9aab664368968ed15c90
Looks like the following bug has the changes which introduced the regression:
https://bugzilla.mozilla.org/show_bug.cgi?id=1315650
- Attached a screen recording of the issue:
search suggestions are no longer displayed after typing a keyword

### PR DESCRIPTION
**Pull request by sarracini**
remoteTimeout was throwing the error - it seems as though it's been deprecated from ContentSearch.jsm - which is where this code originally comes from. As seen here:
https://dxr.mozilla.org/mozilla-central/source/browser/modules/ContentSearch.jsm#270-271

If they don't need it then neither do we. And we're not using it anywhere in the repo either

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-stream/1936)

### CODE REVIEW

File: addon/SearchProvider.js [hunk 1]
```diff
@@ -174,7 +174,6 @@ SearchProvider.prototype = {
     let ok = SearchSuggestionController.engineOffersSuggestions(engine);
     controller.maxLocalResults = ok ? MAX_LOCAL_SUGGESTIONS : MAX_SUGGESTIONS;
     controller.maxRemoteResults = ok ? MAX_SUGGESTIONS : 0;
-    controller.remoteTimeout = data.remoteTimeout || undefined;
```
Comment (k88hudson) [inline addon/SearchProvider.js]: Lol `|| undefined`
