### PR TITLE
fix(test) #1043 fix test failures in TabTracker

### LINKED ISSUE #1043: Intermittent failure: ./test/test-TabTracker.test_TabTracker_History_And_Bookmark_Reporting: timed out, failure
I found this running this [unbranded](http://archive.mozilla.org/pub/firefox/tinderbox-builds/mozilla-release-macosx64-add-on-devel/1469543944/firefox-48.0.en-US.mac64-add-on-devel.dmg) 48 build with `JPM_FIREFOX_BINARY=~/Unbranded.app/Contents/MacOS/firefox npm run test:jpm`.

```
console.error: activity-streams: 
  fail:
  Timed out (after: Nothing in bookmarks)
console.info: activity-streams: pass: This test is done.
console.error: activity-streams: 
  fail:
  Should not be any unexpected tabs open
console.trace: activity-streams: 
_ecated/unit-test.js 108 fail
_ecated/unit-test.js 346 done/<
_/Promise-backend.js 937 Handler.prototype.process
_/Promise-backend.js 816 this.PromiseWalker.walkerLoop
_/Promise-backend.js 750 this.PromiseWalker.scheduleWalkerLoop/<
```

### PR DESCRIPTION
**Pull request by ncloudioj**
Fix #1043, #1044, #1080

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-stream/1133)

### CODE REVIEW

File: test/test-TabTracker.js [hunk 1]
```diff
@@ -67,57 +70,87 @@ function checkLoadUnloadReasons(assert, pingData, expectedLoadReasons, expectedU
...
+      Services.obs.removeObserver(onNotify, "tab-session-complete");
+      tabData.notifyData = JSON.parse(data);
+      resolve();
     }
+    Services.obs.addObserver(onNotify, "tab-session-complete", false);
+  });
+
+  yield promiseOnTabShow;
+  yield new Promise(resolve => {
+    tabData.tab.close(() => {
```
Comment (rlr) [inline test/test-TabTracker.js]: nit: you can just do `tabData.tab.close(resolve);`

File: test/test-TabTracker.js [hunk 2]
```diff
@@ -67,57 +70,87 @@ function checkLoadUnloadReasons(assert, pingData, expectedLoadReasons, expectedU
...
+    function onPerfLogComplete(subject, topic, data) {
+      Services.obs.removeObserver(onPerfLogComplete, "performance-log-complete");
+      resolve();
+    }
+    Services.obs.addObserver(onPerfLogComplete, "performance-log-complete", false);
+  });
+
+  yield Promise.all([promiseOnTabShow, promiseOnPerfLogComplete]);
+  yield new Promise(resolve => {
+    tabData.tab.close(() => {
```
Comment (rlr) [inline test/test-TabTracker.js]: same here ☝️

File: test/test-TabTracker.js [hunk 3]
```diff
@@ -589,18 +618,36 @@ exports.test_TabTracker_History_And_Bookmark_Reporting = function*(assert) {
...
+      onReady: tab => {
+        tabData.tab = tab;
+        resolve();
+      }
+    });
+  });
+
+  yield promiseOnTabReady;
+  yield new Promise(resolve => {
+    tabData.tab.close(() => {
```
Comment (rlr) [inline test/test-TabTracker.js]: here too 👆

**Comment by rlr** [comment]
all green locally for me 💃 R+ once travis is happy too
