### PR TITLE
fix (addon): #1711 use OS specific share icon in toolbar

### LINKED ISSUE #1711: Share icon needs to be tailored to the host system
Particularly Windows user have a hard time recognizing the current share icon, which is only commonly used on Mac/iOS. 

We should use the Windows specific share icon for Windows users. 

image
Mac, Windows,  Linux

### PR DESCRIPTION
**Pull request by rlr**
r? @ncloudioj can you test on linux?

Fixes #1711

### CODE REVIEW

File: addon/ShareProvider.js [hunk 1]
```diff
@@ -403,7 +404,14 @@ ShareProvider.prototype = {
         if (!node || node.id !== id) {
           return;
         }
-        node.setAttribute("image", data.url("content/img/glyph-share-16.svg"));
```
Comment (pdehaan) [inline addon/ShareProvider.js]: Does anything still use the generic "glyph-share-16.svg", or should we delete that now that we're moving towards OS-specific iconography?

Comment (rlr) [inline addon/ShareProvider.js]: good point! I'll remove that before merging!

Comment (rlr) [inline addon/ShareProvider.js]: actually, I just realized that icon is still used in the context menu. I'll leave that for another time.
