### PR TITLE
fix (metadatastore): parameterize the images SELECT query

### LINKED ISSUE #1679: Audit all the SQL queries in metadata store
Let's take another look at those SQL queries in the `MetadataStore.jsm`. Like what we've found in #1577 , we'd like to avoid following risks:

* SQL query injections
* inefficient queries
* unnecessary data fetches

### PR DESCRIPTION
**Pull request by rlr**
r? @ncloudioj 

Fixes #1679

### CODE REVIEW

File: addon/MetadataStore.js [hunk 1]
```diff
@@ -461,8 +461,11 @@ MetadataStore.prototype = {
            FROM page_metadata AS pm
               JOIN page_metadata_images AS pmi ON pm.id = pmi.metadata_id
               JOIN page_images AS pi ON pi.id = pmi.image_id
-           WHERE pm.id = ${metaObject.id}`,
-           {columns: ["url", "type", "height", "width", "color"]}
+           WHERE pm.id = :metaobject_id`,
```
Comment (ncloudioj) [inline addon/MetadataStore.js]: Ah, good kill. 👍
