### PR TITLE
fix (addon): #2102 handle exceptions/rejects from _computeImageSize()

### LINKED ISSUE #2102: `undefined` error in PreviewProvider
Activity Stream Version: 1.3.0-dev-1485541569-7dacdd1

Error in browser console:

screenshot 2017-01-30 13 58 58

### PR DESCRIPTION
**Pull request by rlr**
r? @jaredkerim 

Fixes #2102

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-stream/2132)

### CODE REVIEW

File: test/test-PreviewProvider-MetadataStore.js [hunk 1]
```diff
@@ -101,6 +101,48 @@ exports.test_get_links_from_metadatastore = function*(assert) {
...
+  yield gPreviewProvider.asyncSaveLinks(links);
+
+  // asyncSaveLinks doesn't yield on inserting in the db so we need to wait
+  // until it has successfully finished the transaction before checking
+  yield waitUntil(() => !gMetadataStore.transactionInProgress);
+
+  // check that it inserted the link that was filtered out
+  items = yield gMetadataStore.asyncExecuteQuery("SELECT * FROM page_metadata");
+  assert.equal(items.length, 4, "it should now have a length of 4");
+  assert.equal(items[3][1], links[2].cache_key, "it newly inserted the one we didn't already have");
```
Comment (jaredkerim) [inline test/test-PreviewProvider-MetadataStore.js]: This ordering is arbitrary, this could decide to spontaneously fail.  Try something like `order by url` in the sql statement just to ensure that the order is consistent each test run.

Comment (rlr) [inline test/test-PreviewProvider-MetadataStore.js]: 👍
