### PR TITLE
fix (addon+content): #2705 remove highlights

### LINKED ISSUE #2705: Remove Highlights section
Once #2622 (Visits Again Section) lands we can remove the Highlights section and related code that isn't shared with Recent Bookmarks or Visit Again.

### PR DESCRIPTION
**Pull request by rlr**
Fixes #2705

### CODE REVIEW

File: common/constants.js [hunk 1]
```diff
@@ -51,10 +47,8 @@ module.exports = {
   NEWTAB_PREFS_ENCODING: {
     "showSearch": 1 << 0,
     "showTopSites": 1 << 1,
-    "showHighlights": 1 << 2,
     "showMoreTopSites": 1 << 3,
     "showPocket": 1 << 4,
-    "collapseHighlights": 1 << 5,
```
Comment (rlr) [inline common/constants.js]: @ncloudioj is it ok to remove these two lines above ^^

File: content-src/components/Spotlight/Spotlight.js [hunk 2]
```diff
@@ -117,64 +114,6 @@ function renderPlaceholderList() {
...
-  sites: React.PropTypes.array.isRequired,
-  length: React.PropTypes.number,
-  prefs: React.PropTypes.object
-};
-
-module.exports = connect(justDispatch)(Spotlight);
-module.exports.Spotlight = Spotlight;
 module.exports.SpotlightItem = SpotlightItem;
 module.exports.PlaceholderSpotlightItem = PlaceholderSpotlightItem;
 module.exports.renderPlaceholderList = renderPlaceholderList;
```
Comment (piatra) [inline content-src/components/Spotlight/Spotlight.js]: I think this also needs to go together with the component.

Comment (rlr) [inline content-src/components/Spotlight/Spotlight.js]: I left it because it's still used in `content-src/components/PocketStories/PocketStories.js`. We probably want to rename this file from `Spotlight/Spotlight.js` to something more generic. `<something>Cards.js` or something.

Comment (piatra) [inline content-src/components/Spotlight/Spotlight.js]: 👍 but probably save the rename for a future port of the components.

File: common/constants.js (hunk 1 above)
Comment (ncloudioj) [inline common/constants.js]: @rlr yup, it's fine.

**Comment by rlr** [comment]
@piatra I left the "Highlight" mentions in `experiments.json` for historical purposes because those are all retired/graduated experiments. Cleaned up the rest.

**Comment by as-pine-proxy** [comment]
[Treeherder: 1a0514192878a3630cc2cedbbb7147ad95ab2244](https://treeherder.mozilla.org/#/jobs?repo=pine&revision=1a0514192878a3630cc2cedbbb7147ad95ab2244)
