### PR TITLE
fix(tests): Add mochitests that run successfully whether enabled or not

### LINKED ISSUE #2880: Add mochitest to ensure correct behavior enabled/disabled on all channels
There's some complexity here in that for initial rollout, activity-stream is enabled on nightly 56 and disabled beta 56. And beta 56 doesn't even build the extension.

This is to make sure tests don't start failing because of a nightly -> beta transition where build/default prefs change.

### PR DESCRIPTION
**Pull request by Mardak**
Fix #2880. r?@dmose Beefs up `as_load_location` to work preloaded or not and activity-stream.enabled or not. Adds a `head.js` that turns on activity-stream with a set of basic actual react rendering tests covering some of those itemized in #2127. Also cleans up eslint to use the fancy "plugin:mozilla/browser-test" that auto-globalizes-head.js helpers (and other test globals).

Try looks good when a-s.enabled: https://treeherder.mozilla.org/#/jobs?repo=try&revision=2b1081f19bfc7b5adbd761e347a26fd264b55783
And disabled: https://treeherder.mozilla.org/#/jobs?repo=try&revision=34f4c5cf8fbe1c0e2933c429e270e03817b55b2c

### CODE REVIEW

File: system-addon/bootstrap.js [hunk 1]
```diff
@@ -78,6 +78,7 @@ function init(reason) {
 function uninit(reason) {
   if (activityStream) {
     activityStream.uninit(reason);
+    activityStream = null;
```
Comment (Mardak) [inline system-addon/bootstrap.js]: This is to allow tests to clear/disable activity-stream and immediately uninstall (which resulted in back-to-back `uninit`s).

Comment (dmose) [inline system-addon/bootstrap.js]: How about adding a comment to the code to this effect?

File: system-addon/test/functional/mochitest/browser_as_load_location.js [hunk 2]
```diff
@@ -1,34 +1,48 @@
...
- * XXX /browser/components/newtab/tests/browser/browser_newtab_overrides in
- * mozilla-central is where this test was adapted from.  Once we get decide on
- * and implement how we're going to set the URL in mozilla-central, we may well
- * want to (separately from this test), clone/adapt that entire file for our
- * new setup.
- */
-add_task(async function checkActivityStreamLoads() {
-  const asURL = "resource://activity-stream/data/content/activity-stream.html";
-
+// Helper to test that a newtab page loads
```
Comment (dmose) [inline system-addon/test/functional/mochitest/browser_as_load_location.js]: JSDoc would be nice here

File: system-addon/test/functional/mochitest/browser_as_load_location.js [hunk 3]
```diff
@@ -1,34 +1,48 @@
...
+  gBrowser.removePreloadedBrowser();
+  await checkActivityStreamLoads();
+});
+
+// Run a second time from a preloaded browser
+add_task(checkActivityStreamLoads);
+
+// Test with activity stream off
+async function checkNotActivityStreamLoads() {
+  await SpecialPowers.pushPrefEnv({set: [["browser.newtabpage.activity-stream.enabled", false]]});
```
Comment (dmose) [inline system-addon/test/functional/mochitest/browser_as_load_location.js]: Does this need to be popped manually in cleanup somewhere, since it's not in a scopedPushPrefs?

File: system-addon/test/functional/mochitest/head.js [hunk 4]
```diff
@@ -0,0 +1,93 @@
...
+    let tab = await BrowserTestUtils.openNewForegroundTab(gBrowser, "about:newtab", false);
+
+    // Specially wait for potentially preloaded browsers
+    let browser = tab.linkedBrowser;
+    await waitForPreloaded(browser);
+
+    // Wait for React to render something
+    await BrowserTestUtils.waitForCondition(() => ContentTask.spawn(browser, {},
+      () => content.document.getElementById("root").children.length),
+      "Should render activity stream content");
```
Comment (dmose) [inline system-addon/test/functional/mochitest/head.js]: I'm a little concerned that this could race, since just because root has children doesn't necessarily tell us much about how far along rendering is.  That said, I don't have a better suggestion.

File: system-addon/test/functional/mochitest/head.js [hunk 5]
```diff
@@ -0,0 +1,93 @@
...
+      let contentArg = await before({pushPrefs: scopedPushPrefs, tab});
+      let contentResult = await ContentTask.spawn(browser, contentArg, contentTask);
+      await after(contentResult);
+    } finally {
+      // Clean up for next tests
+      await scopedPopPrefs();
+      await BrowserTestUtils.removeTab(tab);
+    }
+  };
+
```
Comment (dmose) [inline system-addon/test/functional/mochitest/head.js]: This is great.  Someday, it (or something like it) should be hoisted somewhere more central in m-c so that it's generally available.

File: system-addon/test/functional/mochitest/head.js [hunk 6]
```diff
@@ -0,0 +1,93 @@
...
+// Activity Stream tests expect it to be enabled, and make sure to clear out any
+// preloaded browsers that might have about:newtab that we don't want to test
+const ACTIVITY_STREAM_PREF = "browser.newtabpage.activity-stream.enabled";
+pushPrefs([ACTIVITY_STREAM_PREF, true]);
+gBrowser.removePreloadedBrowser();
+
+/**
+ * Helper to wait for potentially preloaded browsers to load
+ */
```
Comment (dmose) [inline system-addon/test/functional/mochitest/head.js]: Probably worth pointing out in the comment that this is effectively the "load" event, and contains no guarantee about what has or hasn't been rendered.

File: system-addon/test/functional/mochitest/browser_as_load_location.js (hunk 3 above)
Comment (Mardak) [inline system-addon/test/functional/mochitest/browser_as_load_location.js]: The purpose of the push is so that it does autopop.... at the end of the whole test run it seems.

File: system-addon/test/functional/mochitest/browser_as_load_location.js (hunk 2 above)
Comment (Mardak) [inline system-addon/test/functional/mochitest/browser_as_load_location.js]: Added

File: system-addon/test/functional/mochitest/head.js (hunk 6 above)
Comment (Mardak) [inline system-addon/test/functional/mochitest/head.js]: Commented

File: system-addon/test/functional/mochitest/head.js (hunk 4 above)
Comment (Mardak) [inline system-addon/test/functional/mochitest/head.js]: Sooooooo… this was very odd to add in the first place, and it's mostly a sanity check instead of an even odder looks-like-no-op. From my testing on slower debug builds, it looks to always match the condition on the first check.

In fact, by doing a `await ContentTask.spawn(browser, {}, () => {})`, enough time will have passed from sending and waiting for the message. However, without doing that "nothing", tests fail because there's no data for React to `render`. React is actually rendering null resulting in an empty comment, e.g., https://stackoverflow.com/questions/38923805/what-is-react-empty

File: system-addon/bootstrap.js (hunk 1 above)
Comment (Mardak) [inline system-addon/bootstrap.js]: Commented

File: system-addon/test/functional/mochitest/head.js (hunk 5 above)
Comment (Mardak) [inline system-addon/test/functional/mochitest/head.js]: The chaining? I suppose it's "overengineered" in that I didn't quite use all the functionality in the actual tests, but it did get me to write some additional actual activity-stream related tests to make sure the helper actually worked. :)

**Comment by as-pine-proxy** [comment]
[Treeherder: b9633b96829d377682ed260d4cd2d93abfdecf5f](https://treeherder.mozilla.org/#/jobs?repo=pine&revision=b9633b96829d377682ed260d4cd2d93abfdecf5f)
