### PR TITLE
fix(addon): Closes #1480 Create an init function for ActivityStreams

### LINKED ISSUE #1480: Make the ActivityStream constructor not have side effects
Seriously we should have an init function and not a giant constructor for activity stream. It'll help split out a bunch of logic that doesn't belong in a constructor and will help with testing most likely

### PR DESCRIPTION
**Pull request by sarracini**
Fix #1480.
* Creates an initialization function for Activity Stream
* Removes all side effects of the constructor

### CODE REVIEW

**Comment by k88hudson** [comment]
I will take a look this afternoon

File: addon/ActivityStreams.js [hunk 1]
```diff
@@ -227,6 +172,117 @@ ActivityStreams.prototype = {
...
+    this._tabTracker = new TabTracker(
+      this.appURLs,
+      this.options.clientID,
+      memoized,
+      experimentProviderID
+    );
+  },
+
+  _initializeExperimentProvider() {
+    this._experimentProvider = new ExperimentProvider(
```
Comment (k88hudson) [inline addon/ActivityStreams.js]: You could actually initialize this in the constructor since has no side effects, and just call `_experimentProvider.init` directly.

File: addon/ActivityStreams.js [hunk 2]
```diff
@@ -227,6 +172,117 @@ ActivityStreams.prototype = {
     });
   },
 
+  _setUpPageWorker(store) {
+    this._pageWorker = new PageWorker({store});
+    this._pageWorker.connect();
+    this._refreshAppState();
```
Comment (k88hudson) [inline addon/ActivityStreams.js]: What do you think abt putting `buildAsyncCache` and `refreshAppState` in their own separate method? since they are both kind of related to initializing the data for the app

Comment (k88hudson) [inline addon/ActivityStreams.js]: It feels kind of weird here

Comment (sarracini) [inline addon/ActivityStreams.js]: sure - ```initializeAppData``` for a name?

**Comment by k88hudson** [comment]
Hmm, tests are failing. Intermittents?

File: addon/ActivityStreams.js [hunk 3]
```diff
@@ -218,6 +172,99 @@ ActivityStreams.prototype = {
     });
   },
 
+  _initializeAppData() {
```
Comment (k88hudson) [inline addon/ActivityStreams.js]: 👍

**Comment by sarracini** [comment]
oops that's my bad, deleted something i shouldn't have when i was rebasing. updated PR should be fixed now

**Comment by k88hudson** [comment]
Ok, looks good!
