### PR TITLE
fix(content): #632 Bug 1269777 - Google search string from context menu wrongly searches

### LINKED ISSUE #632: Bug 1269777 - Google search string from context menu wrongly searches also after the host name initial
via https://bugzilla.mozilla.org/show_bug.cgi?id=1269777
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.14-dev-1462225209

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.14-dev-1462225209) was previously installed on a clean profile.
- Have at least one website in "Highlights" or "Recent Activity" area from Activity Stream Timeline.  

[Steps to reproduce]:
1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Click on "Activity Stream" button from browser toolbar.
3. Right click on any website from "Highlights" or "Recent Activity".
4. Click on "Search Google for "..."" from the context menu.

[Expected results]:
Only visible strings are displayed in Google search bar. 

[Actual results]:
Hidden strings are also displayed in Google search bar.

[Notes]:
- The hidden string is the first letter of the URL.
- In my opinion, the best user experience would be to search only after the page title not also the page link and time-stamp.   
- The issue is reproducible on the New Tab page as well.
- Attached a screenshot of the issue.
hidden string

### PR DESCRIPTION
**Pull request by sarracini**
@k88hudson r?

Fixes #632 

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-stream/734)

### CODE REVIEW

File: content-src/components/SiteIcon/SiteIcon.js [hunk 1]
```diff
@@ -34,7 +34,7 @@ const SiteIcon = React.createClass({
       <div ref="border" hidden={!showBackground || !showBorder} className="inner-border" />
       <div className="site-icon-wrapper">
         <img ref="favicon" width={faviconSize} height={faviconSize} className="site-icon-favicon" hidden={showFallback} src={site.favicon} />
-        <span ref="fallback" className="site-icon-fallback" style={fallbackStyle} hidden={!showFallback}>{site.firstLetter}</span>
+        <span ref="fallback" className="site-icon-fallback" style={fallbackStyle} hidden={!showFallback} data-first-letter={site.firstLetter}></span>
```
Comment (k88hudson) [inline content-src/components/SiteIcon/SiteIcon.js]: you can make this a self-closing tag now that there is no content

**Comment by k88hudson** [comment]
R+, just one small nit 👍
