### PR TITLE
fix(addon): #1756 - fix a race condition in TabTracker

### LINKED ISSUE #1756: TabTracker race
When @k88hudson and I were pairing, we saw a console error where isActivityStreamsURL blew up because it was called before this._trackableURLs had been set (i.e. presumably a new tab had been opened after the TabTracker constructor had been called, but before TabTracker.init had finished).

We speculated that a reasonable fix would be to moving more of the side-effecty stuff out of the constructor and into init (in particular, we shouldn't be setting up any listeners before init is called).

### PR DESCRIPTION
**Pull request by ncloudioj**
This closes #1756

### CODE REVIEW

File: addon/TabTracker.js [hunk 1]
```diff
@@ -43,6 +35,14 @@ TabTracker.prototype = {
     this._trackableURLs = trackableURLs;
     this._experimentID = experimentId;
     this._store = store;
+
+    this.onOpen = this.onOpen.bind(this);
```
Comment (k88hudson) [inline addon/TabTracker.js]: Technically this could stay in the constructor, although I guess it's fine to have it here

File: addon/TabTracker.js [hunk 2]
```diff
@@ -43,6 +35,14 @@ TabTracker.prototype = {
...
+    this.enabled = simplePrefs.prefs[TELEMETRY_PREF];
+    if (this.enabled) {
+      this._addListeners();
+    }
+    this._onPrefChange = this._onPrefChange.bind(this);
```
Comment (k88hudson) [inline addon/TabTracker.js]: Same with this
