### PR TITLE
Handle exceptions if the addon couldn't connect to Metadatastore

### LINKED ISSUE #1002: Unhandled exception in metadata store async connect
This keeps appearing in my browser console:

A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Fri Jul 29 2016 11:19:40 GMT-0400 (EDT)
Full Message: TypeError: aId is undefined
Full Stack: CustomizableUIInternal.isSpecialWidget@resource://app/modules/CustomizableUI.jsm:1239:5
CustomizableUIInternal.getWidgetProvider@resource://app/modules/CustomizableUI.jsm:860:9
CustomizableUIInternal.wrapWidget@resource://app/modules/CustomizableUI.jsm:471:20
this.CustomizableUI.createWidget@resource://app/modules/CustomizableUI.jsm:3265:12
create@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/ui/button/view.js:122:3
setup@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/ui/button/action.js:60:5
@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/core/disposable.js:45:56
dispatch@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/method/core.js:119:12
Disposable<.initialize@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/core/disposable.js:135:17
constructor@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/core/heritage.js:146:23
_setupButton@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/lib/ActivityStreams.js:514:20
ActivityStreams@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/lib/ActivityStreams.js:75:3
main/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/lib/main.js:27:13
TaskImpl_run@resource://gre/modules/Task.jsm:319:40
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:937:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:816:7
Promise*this.PromiseWalker.scheduleWalkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:747:11
this.PromiseWalker.schedulePromise@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:779:7
this.PromiseWalker.completePromise@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:714:7
TaskImpl_run@resource://gre/modules/Task.jsm:324:13
Async*TaskImpl_handleResultValue@resource://gre/modules/Task.jsm:395:7
TaskImpl_run@resource://gre/modules/Task.jsm:327:13
TaskImpl@resource://gre/modules/Task.jsm:280:3
createAsyncFunction/asyncFunction@resource://gre/modules/Task.jsm:254:14
MetadataStore.prototype.asyncConnect<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/lib/MetadataStore.js:135:13
TaskImpl_run@resource://gre/modules/Task.jsm:319:40
Async*TaskImpl_handleResultValue@resource://gre/modules/Task.jsm:395:7
TaskImpl_run@resource://gre/modules/Task.jsm:327:13
Async*TaskImpl_handleResultValue@resource://gre/modules/Task.jsm:395:7
TaskImpl_run@resource://gre/modules/Task.jsm:327:13
Async*TaskImpl_handleResultValue@resource://gre/modules/Task.jsm:395:7
TaskImpl_run@resource://gre/modules/Task.jsm:327:13
TaskImpl@resource://gre/modules/Task.jsm:280:3
createAsyncFunction/asyncFunction@resource://gre/modules/Task.jsm:254:14
main/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/lib/main.js:26:13
TaskImpl_run@resource://gre/modules/Task.jsm:319:40
Async*TaskImpl_handleResultValue@resource://gre/modules/Task.jsm:395:7
TaskImpl_run@resource://gre/modules/Task.jsm:327:13
TaskImpl@resource://gre/modules/Task.jsm:280:3
createAsyncFunction/asyncFunction@resource://gre/modules/Task.jsm:254:14
Task_spawn@resource://gre/modules/Task.jsm:168:12
main@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/lib/main.js:23:5
run@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/addon/runner.js:153:7
startup/</<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/addon/runner.js:87:9
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:937:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:816:7
Promise*this.PromiseWalker.scheduleWalkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:747:11
this.PromiseWalker.schedulePromise@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:779:7
this.PromiseWalker.completePromise@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:714:7
handler@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/addon/window.js:56:3
EventListener.handleEvent*EventTargetInterposition.methods.addEventListener@resource://gre/modules/RemoteAddonsParent.jsm:652:5
AddonInterpositionService.prototype.interposeProperty/desc.value@resource://gre/components/multiprocessShims.js:160:52
@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/addon/window.js:54:1
evaluate@resource://gre/modules/commonjs/toolkit/loader.js:279:19
load@resource://gre/modules/commonjs/toolkit/loader.js:331:5
_require@resource://gre/modules/commonjs/toolkit/loader.js:671:16
require@resource://gre/modules/commonjs/toolkit/loader.js:625:12
startup/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/addon/runner.js:72:21
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:937:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:816:7
Promise*this.PromiseWalker.scheduleWalkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:747:11
this.PromiseWalker.schedulePromise@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:779:7
this.PromiseWalker.completePromise@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:714:7
readURI/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/net/url.js:50:9
NetUtil_asyncFetch/<.onStopRequest@resource://gre/modules/NetUtil.jsm:128:17

It's talking about metadata store async connect here:

https://github.com/mozilla/activity-stream/blob/master/lib/MetadataStore.js#L135

### PR DESCRIPTION
**Pull request by ncloudioj**
This fixes #1002

Note that those two commits are closely related. The first one adds the database reconnecting feature, and the other one reinforces the exception handling in the case that the connection is either unopened or closed in the MetadataStore.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-stream/1019)

### CODE REVIEW

File: lib/main.js [hunk 1]
```diff
@@ -23,21 +30,45 @@ Object.assign(exports, {
...
 
+  reconnectMetadataStore() {
+    if (connectRetried > kMaxConnectRetry) {
+      throw new Error("Metadata store reconnecting has reached the maximum limit");
+    }
+
+    this.reconnectTimeoutID = setTimeout(function() {
+      metadataStore.asyncConnect().catch(error => {
+        // increment the connect counter to avoid the endless retry
+        connectRetried++;
```
Comment (oyiptong) [inline lib/main.js]: we should reset `connectRetried` to zero on successful connection

Comment (ncloudioj) [inline lib/main.js]: Oops. Good kill 👍. It is now fixed!

**Comment by oyiptong** [comment]
r+
